# Generated by Django 4.2.11 on 2024-04-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('blog', '0002_remove_post_like_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='follow', to='authentication.myuser'),
        ),
    ]
